### ISSUE TITLE
Windows defender detects DOOM.EXE as malware

### ISSUE THREAD

**Issue by cornzz** [nneonneo/universal-doom#2]
This happened after I exited the game

![image](https://user-images.githubusercontent.com/39997278/101358621-66294880-389b-11eb-9344-9dc738bf12d4.png)

**Comment by nneonneo** [comment]
That's odd, because the new non-UPX DOOM.EXE (committed last week) is not detected by any AV engines: https://www.virustotal.com/gui/file/5ca97717fd79f833b248ae5985fffadbee39533f5e0529bc9d7b439e08b8f1d2/detection. The SHA256 of this file is 5ca97717fd79f833b248ae5985fffadbee39533f5e0529bc9d7b439e08b8f1d2 - make sure you have the right version.

The previous version of the file, DOOMUPX.EXE (previously called DOOM.EXE; SHA256 d395f426ed2b7701c09313157297a47ce94f9d767ea089079bc36783b55374c6) was detected by a bunch of engines, presumably for being a UPX executable with unusual headers. See Issue #1.

It's possible this is a false alarm; see https://github.com/tarkah/grout/issues/35 for an example case. If so, you're encouraged to submit it to Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission. Please check the SHA256 file hashes before submitting, to ensure that you didn't get a corrupted or actually infected file somehow.
